name: Run Titanic ETL

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL
        run: python etl_titanic.py
